'use client'

import { useMemo } from 'react'
import { Clause } from '@/lib/api'

interface ReportGeneratorProps {
  clauses: Clause[]
  documentSummary?: string
  filename?: string
}

export default function ReportGenerator({ clauses, documentSummary, filename }: ReportGeneratorProps) {
  const report = useMemo(() => {
    const high = clauses.filter(c => c.category === 'Red')
    const medium = clauses.filter(c => c.category === 'Yellow')
    const low = clauses.filter(c => c.category === 'Green')

    let md = `# Legal Analysis Report\n`
    md += `**Document:** ${filename || 'Unknown'}\n`
    md += `**Generated:** ${new Date().toLocaleDateString()}\n\n`
    md += `---\n\n`

    if (documentSummary) {
      md += `## Executive Summary\n\n${documentSummary}\n\n`
    }

    md += `## Risk Overview\n\n`
    md += `| Category | Count |\n|----------|-------|\n`
    md += `| 🔴 High Risk | ${high.length} |\n`
    md += `| 🟡 Medium Risk | ${medium.length} |\n`
    md += `| 🟢 Low Risk | ${low.length} |\n`
    md += `| **Total** | **${clauses.length}** |\n\n`

    const addClauseSection = (title: string, items: Clause[]) => {
      if (items.length === 0) return
      md += `## ${title}\n\n`
      items.forEach((c, i) => {
        md += `### ${i + 1}. ${c.type} (p.${c.page_number})\n\n`
        if (c.summary) md += `**Summary:** ${c.summary}\n\n`
        md += `**Risk:** ${c.explanation}\n\n`
        md += `**Score:** ${(c.score * 100).toFixed(0)}%\n\n`
        if (c.entities?.length) {
          md += `**Entities:** ${c.entities.map(e => `${e.text} (${e.type})`).join(', ')}\n\n`
        }
        md += `> ${c.text.slice(0, 300)}${c.text.length > 300 ? '...' : ''}\n\n`
      })
    }

    addClauseSection('🔴 High Risk Clauses', high)
    addClauseSection('🟡 Medium Risk Clauses', medium)
    addClauseSection('🟢 Low Risk Clauses', low)

    md += `---\n\n*Report generated by Vidhived.ai*\n`
    return md
  }, [clauses, documentSummary, filename])

  const downloadMarkdown = () => {
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `analysis-report-${new Date().toISOString().slice(0, 10)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex gap-2">
      <button onClick={downloadMarkdown} className="btn btn-ghost text-xs">
        📥 Export Report
      </button>
    </div>
  )
}